Support subgraph datasources
graphprotocol/graph-tooling pull request #1754
Opened 2024-11-05 08:11 UTC by incrypto32

This PR adds new types for subgraph datasources to graph-ts and codegen functionality to generate schema code for the source subgraphs

2024-11-05 20:20 UTC, 0237h commented
Hey @incrypto32, thanks for the PR !

Gonna take a bit of time to review. In the meantime if you can provide some more context/information as to what these feature would bring to developers, would be very much appreciated thanks :+1:

2024-11-07 15:56 UTC, 0237h commented
Given the context, we'll also wait for some of the [related PRs](https://github.com/search?q=repo%3Agraphprotocol%2Fgraph-node+composition++&type=pullrequests&state=open) in [`graph-node`](https://github.com/graphprotocol/graph-node/) to be merged before merging this one as well.

2024-11-07 16:08 UTC, incrypto32 commented
Hey @0237h , i'll write up the required context soon. TL;DR is this will support the code generation and the new type of datasource thats being added as part of the subgraph composition feature. As you mentioned. Yes those graph-node PR's need to be merge before getting this out. I'll write a detailed comment on the changes later.

2024-11-14 16:30 UTC, incrypto32 commented
@0237h I just added a description to the PR. let me know if more info is needed

2024-11-15 15:32 UTC, 0237h requested changes
@incrypto32 Thanks for the updated description !

A few minor comments, other LGTM.
Do you know if the `graph-node` integration for subgraph datasources is also ready ?

2024-11-15 15:32 UTC, 0237h commented on packages/cli/src/type-generator.ts
> +  async loadSubgraphSchemaFromIPFS(ipfsClient: any, manifest: string) {
Could we add some tests for this method ?

2024-11-15 15:32 UTC, 0237h commented on packages/cli/src/protocols/index.ts
> +  mappingScaffold: undefined,
Any reason we're not using the [subgraph scaffolds](https://github.com/graphprotocol/graph-tooling/tree/b45cf7361075df227c4a3699d884070c02d121b5/packages/cli/src/protocols/subgraph/scaffold) here ?

2024-11-15 15:32 UTC, 0237h commented on packages/cli/src/protocols/subgraph/subgraph.ts
> +export default class SubgraphDS implements Subgraph {
I think `SubgraphDataSource` would be more explicit.

2024-11-22 14:49 UTC, YaroShkvorets commented
Doesn't seem to work for me. After running `graph init` and selecting "subgraph" as a protocol it tries to download ABI for I don't know what. I assume it shouldn't, since I never specified the contract address?
What's the flow here @incrypto32 ? 

<img width="749" alt="image" src="https://github.com/user-attachments/assets/0847a41b-ed27-4baf-9aa1-e6435de92466">

2024-11-22 16:46 UTC, incrypto32 commented
Oops, i think i didn't check the `graph init` support just the codegen and build. I tested with an existing subgraph that i modified to use the new datasource. 
Thanks for testing it out @YaroShkvorets, i'll add the init support too.

2024-11-28 12:07 UTC, incrypto32 commented
@YaroShkvorets just added the init command. Please re review

2024-11-29 21:26 UTC, YaroShkvorets commented
```
❯ ./bin/run init --skip-install --skip-git
 ›   Warning: @graphprotocol/graph-cli update available from 0.87.0 to 0.90.1.
 ›   Warning: In next major version, this flag will be removed. By default we will stop initializing a Git repository.
✔ Protocol · subgraph
✔ Subgraph slug · asdf
✔ Directory to create the subgraph in · asdf
? Subgraph network …
? Subgraph network …
? Subgraph network …
✔ Subgraph network · mainnet
✔ Source subgraph identifier · QmTZ8ejXJxRo7vDBS4uwqBeGoxLSWbhaA7oXa1RvxunLy7
✔ IPFS node to use for fetching subgraph manifest · https://api.thegraph.com/ipfs/api/v0
✔ Start Block · 0
  Generate subgraph
✖ Failed to create subgraph scaffold: Cannot read properties of undefined (reading 'length')
    TypeError: Cannot read properties of undefined (reading 'length')
```

2024-11-29 21:32 UTC, YaroShkvorets commented
Let's merge it @0237h , then let @incrypto32 polish out any bugs.
There is a lot of overlap with what I'm doing so I don't want to keep this PR open much longer to avoid merge hell.

2024-11-29 21:33 UTC, YaroShkvorets approved these changes

2024-11-29 22:03 UTC, merged

2024-12-02 06:07 UTC, incrypto32 commented
@YaroShkvorets as will this be released soon?
Actually we need to wait before releasing this for the graph-node PR's to be merged. cc: @alex-pakalniskis 
https://github.com/graphprotocol/graph-tooling/pull/1754#issuecomment-2462599489

2024-12-02 14:29 UTC, YaroShkvorets commented
Yes, let's coordinate on the release.