fix: honor --contract-name and --start-block
graphprotocol/graph-tooling pull request #1778
Opened 2024-11-29 09:16 UTC by briceyan

2024-11-29 17:51 UTC, 0237h commented
Hey @briceyan, thanks for the PR. Would you mind adding a description of the fix ?

I understand it fixes an issue with the `add` command not respecting flag parameters and I could reproduce the issue, appreciate the fix.

2024-11-30 03:56 UTC, briceyan commented
I initially suspected that the process hanging after completing the code generation was caused by some leftover async operations, but it now seems likely that prompt.ask is the reason for the hang. Unfortunately, I don’t have enough time to investigate this further at the moment—apologies for the incomplete diagnosis.

Below is the output when I ran the command with [why-is-node-running](https://www.npmjs.com/package/why-is-node-running):

------
...
+ why-is-node-running /Users/brice/Devel/graph-tooling/packages/cli/bin/run add --abi /Users/brice/EverythingFun/v1-core/out/ISet.sol/ISet.json --merge-entities --contract-name Set12 --start-block 1 0x0000000000000000000000000000000000000000
probing program /Users/brice/Devel/graph-tooling/packages/cli/bin/run
kill -SIGUSR1 19346 for logging
(node:19346) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✖ Failed to fetch Contract Name: Failed to fetch contract source code: Contract source code not verified
✔ Contract Name · Set12
✔ Running codegen
There are 17 handle(s) keeping the process running.

# TTYWRAP
/Users/brice/Library/pnpm/global/5/.pnpm/why-is-node-running@3.2.1/node_modules/why-is-node-running/include.js:6 - console.log('kill -SIGUSR1', process.pid, 'for logging')

# TTYWRAP
(unknown stack trace)

# TTYWRAP
/Users/brice/Devel/graph-tooling/node_modules/.pnpm/password-prompt@1.1.3/node_modules/password-prompt/index.js:3 - const stdin = process.stdin

# FILEHANDLE
(unknown stack trace)

# FILEHANDLE
(unknown stack trace)
...

2024-12-03 15:18 UTC, 0237h commented
@briceyan Not sure I fully understand, are you running into some other issue even after the fix of this PR ?

2024-12-11 18:55 UTC, YaroShkvorets requested changes
Thanks for the PR, it was indeed a bug. See my comments.

2024-12-11 18:55 UTC, YaroShkvorets commented on packages/cli/src/commands/add.ts
> +    let startBlock = parseInt(startBlockFlag ?? '').toString();
if `startBlockFlag` is not provided this results in NaN and the whole command fails

2024-12-11 18:55 UTC, YaroShkvorets commented on packages/cli/src/commands/add.ts
> +      contractName ||= await loadContractNameForAddress(network, address);
While we are at it, could you move `contractName` uniqueness check from L87-L94 to below this try-catch so we can capture name loaded from etherscan too

2024-12-11 18:55 UTC, YaroShkvorets commented on packages/cli/tests/cli/add.test.ts
> +        '--start-block',
Add a separate test for case when startBlock is not supplied to avoid NaN bug above

2024-12-13 20:04 UTC, 0237h approved these changes

2024-12-16 03:29 UTC, YaroShkvorets approved these changes

2024-12-16 03:42 UTC, merged