Don't check mandatory fields for null
graphprotocol/graph-tooling pull request #185
Opened 2018-12-12 13:20 UTC by leodasvacas

Helps with #169 and https://github.com/graphprotocol/graph-node/issues/571. This solves those issues for the `Boolean!` graphql type, but not for the optional `Boolean`.

Overall this is a good polish over what we have now, so worth doing regardless of what the final solution to those issues is.

2018-12-14 14:49 UTC, leodasvacas commented
This has been updated to implement the solution we considered to be least bad: Which is to allow `false` and `0` to be returned if the field is missing, requiring the user to use `isSet` to disambiguate. See https://github.com/graphprotocol/graph-ts/pull/31.

2018-12-14 17:34 UTC, Jannis requested changes
Great! One remark: The generated types for the example subgraphs are in `src/`. Can you rerun codegen with `--output-dir=src/types`?

2018-12-14 20:06 UTC, leodasvacas commented
@Jannis Ah well noticed, I did find it strange that the generated types weren't there already.

2018-12-15 00:17 UTC, Jannis approved these changes

2018-12-15 12:02 UTC, merged