Add `graph create` command to create named subgraphs
graphprotocol/graph-tooling pull request #190
Opened 2019-01-09 08:17 UTC by Jannis

Resolves #189.

This also changes the `graph remove` command. Both now have the following signature:

```sh
graph create <SUBGRAPH_NAME> ... # -g/--node, --access-token are supported
graph remove <SUBGRAPH_NAME> ... # -g/--node, --access-token are supported
```

2019-01-11 17:29 UTC, timmclean requested changes
It feels like `graph deploy` should be `graph deploy [SUBGRAPH_NAME] [MANIFEST]` now for consistency

2019-01-11 17:59 UTC, Jannis commented on graph.js
> +  .option('-g, --node <URL>[:PORT]', 'Graph node to create the subgraph in')
That is... true. I'll update.

2019-01-11 18:00 UTC, Jannis commented
@timmclean I do agree about `graph deploy`. Can make that change in a separate PR though. Would you mind creating an issue for that?

2019-01-11 18:04 UTC, timmclean commented
Done! https://github.com/graphprotocol/graph-cli/issues/192

2019-01-13 15:41 UTC, Jannis commented on graph.js
> +  .option('-g, --node <URL>[:PORT]', 'Graph node to create the subgraph in')
Done

2019-01-13 15:42 UTC, Jannis commented
@timmclean Ready for another review pass. I've also added a bunch of other small improvements and fixes.

2019-01-14 02:46 UTC, timmclean commented on graph.js
> +      outputNameAndNodeConfig(cmd, { subgraphNameFromFlag: false, subgraphName })
should `subgraphNameFromFlag` still be here?

2019-01-14 02:47 UTC, timmclean commented on graph.js
> +      outputNameAndNodeConfig(cmd, { subgraphNameFromFlag: false, subgraphName })
ditto on `subgraphNameFromFlag`

2019-01-14 02:55 UTC, timmclean commented
@Jannis re-reviewed

2019-01-14 12:59 UTC, Jannis commented
@timmclean Good catch. Removed the flag from all calls now.

2019-01-14 15:41 UTC, timmclean approved these changes

2019-01-14 15:42 UTC, merged