Top level data source templates
graphprotocol/graph-tooling pull request #319
Opened 2019-07-29 18:10 UTC by leoyvens

See https://github.com/graphprotocol/graph-node/issues/1023. The old format is immediately unsupported, but we print a helpful error message.

2019-08-13 13:51 UTC, Jannis requested changes

2019-08-13 13:51 UTC, Jannis commented on src/validation/manifest.js
> +                                `a \`templates:\` field at the top-level of the manifest.`,
`top-level` -> `top level`. `top level` is the noun, `top-level` is more like an adjective, I think.

2019-08-13 13:51 UTC, Jannis commented on tests/cli/validation.test.js
> +    'deprecated template format gives nice error',
Nit: all test names start with a capital letter so far.

2019-08-13 20:52 UTC, leoyvens commented
@Jannis comments addressed.

2019-08-14 15:32 UTC, fordN approved these changes
Looks good! I just noticed a very minor tense typo, see my comment.

2019-08-14 15:32 UTC, fordN commented on src/type-generator.js
> +            // types generate for data source templates
generated?

2019-08-14 15:50 UTC, leoyvens commented on src/type-generator.js
> +            // types generate for data source templates
Fixed, thanks.

2019-08-15 16:01 UTC, Jannis approved these changes

2019-09-02 15:26 UTC, leoyvens commented
Rebased, and fixed a bug with the output directory of template mappings. @Jannis could you review again?

2019-09-02 16:23 UTC, merged